### ISSUE TITLE
tfb_acquire_fb() failed: Unable to set TTY in graphic mode

### ISSUE THREAD

**Issue by lenniea** [vvaltchev/tfblib#1]
When running on Raspberry Pi I get the following error:

tfb_acquire_fb() failed: Unable to set TTY in graphic mode

in all the examples.  How do I fix/workaround this error?

**Comment by vvaltchev** [comment]
Hi!

Are you in the _actual_ Linux console mode when running the examples?
If you're running in graphic mode, you cannot use the framebuffer because X is using it.
To switch to the linux console (virtual terminal), press Ctrl + Alt + F3, login there and run the examples.

Check this out:
https://www.youtube.com/watch?v=vAr9PM9dEtE&ab_channel=Guru99

Vlad

**Comment by lenniea** [comment]
Is there any way to "share" /dev/fb0 with X in tfblib?  The reason I ask is because fbv (frame buffer viewer) can still open & write to the frame buffer (from a serial console or other login) whereas tfblib errors when opening?

**Comment by vvaltchev** [comment]
It's not a good idea to use /dev/fb0 while X is running, because it's directly mapped to the screen, which is _shared_ with X. Actually, if I don't set the TTY to graphics mode, there won't be any errors, and I could draw to the framebuffer, but after 1/60th of the second, X will update the screen and you won't see anything. This behavior is correct.

But, if you want to draw to the framebuffer from a remote console, while your machine is *not* running X, that's another story. That's totally possible with tfblib. Just pass the `TFB_FL_NO_TTY_KD_GRAPHICS` flag to `tfb_acquire_fb()`. The library won't attempt to set the current TTY in graphics mode and you'll get an unconditional access to the framebuffer. If some other app uses the screen at the same time, or if something writes to the video console there, you'll see your graphics and the other stuff mixed.

Let me know if  `TFB_FL_NO_TTY_KD_GRAPHICS` solved your problem.

Vlad

**Comment by lenniea** [comment]
Yes that solved my problem (on the Raspberry Pi and a different embedded Linux target).

Thanks,
Lennie

**Comment by vvaltchev** [comment]
I'm happy the flag solved your problem :-)
